### ISSUE TITLE
incompatible with python 2.6.6

### ISSUE THREAD

**Issue by hieixu** [knadh/simplemysql#15]
Python 2.6.6 (r266:84292, Sep 11 2012, 08:34:23)
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from simplemysql import SimpleMysql
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.6/site-packages/simplemysql/**init**.py", line 1, in <module>
> > >     from .simplemysql import SimpleMysql
> > >   File "/usr/lib/python2.6/site-packages/simplemysql/simplemysql.py", line 162
> > >     data = {k: data[k] for k in data if k not in keys}
> > >                          ^
> > > SyntaxError: invalid syntax

**Comment by knadh** [comment]
@hieixu The lib has only been tested on 2.7+
