### ISSUE TITLE
Are you going to support binding vars for security?

### ISSUE THREAD

**Issue by VeNoMouS** [knadh/simplemysql#26]
I noticed you are not using binding var's in any statement or `cur.execute`ing with dict's!

Just wondering if you are going to change your security model?

**Comment by VeNoMouS** [comment]
After investigation i discovered that python mysqldb doesn't use prepared statements in the traditional sense, it simply escapes strings, the only library i found that uses MYSQL STMT is `oursql`... STMT is for true binding.

**Comment by knadh** [comment]
:+1:
