### ISSUE TITLE
Disabling and re-enabling autocommit on the fly

### ISSUE THREAD

**Issue by PasqualePuzio** [knadh/simplemysql#32]
Hi,

I want to start a connection with autocommit enabled (autocommit=True, which is fine for most of the operations) and occasionally I want to disable it, run a transaction and then re-enable it.

To do so, I've done as follows:

1. start the connection with autocommit enabled

```python
db = SimpleMysql(
        host="127.0.0.1",
	db="mydatabase",
	user="username",
	passwd="password",
	keep_alive=True,
        autocommit = True
)
```

2. disable autocommit when needed

```python
cursor = db.query("SET autocommit = 0")
```

3. run a bunch of queries, for instance

```python
db.update(...)
db.insert(...)
db.delete(...)
```

4. call commit

```python
db.commit()
```

5. finally, turn autocommit back on

```python
cursor = db.query("SET autocommit = 1")
```

Is that safe or do you think it may cause issues during the connection?

Thanks

**Comment by knadh** [comment]
This shouldn't be a problem. Auto commit would be getting toggled on that particular session and wouldn't affect other sessions.
